# ==============================================================================
# Water Purifier Service Platform - Docker & Dynamic IP Automation Script (Windows)
# ==============================================================================

Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host " 🚀 Water Purifier Platform - Auto-Config & Docker Launcher" -ForegroundColor Cyan
Write-Host "=================================================================" -ForegroundColor Cyan

# 1. Detect Active IPv4 Network Addresses
Write-Host "`n🔍 Detecting active network IP address..." -ForegroundColor Yellow

$ipAddresses = @(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { 
    $_.IPAddress -notlike "127.*" -and 
    $_.IPAddress -notlike "169.254.*" -and 
    $_.InterfaceAlias -notlike "*vEthernet*" -and 
    $_.InterfaceAlias -notlike "*Virtual*" -and 
    $_.InterfaceAlias -notlike "*Loopback*"
} | Select-Object -ExpandProperty IPAddress)

$detectedIp = "localhost"

if ($ipAddresses.Count -gt 0) {
    # Pick first primary WiFi/Ethernet IP
    $detectedIp = $ipAddresses[0]
    Write-Host "✅ Detected Local LAN IP: $detectedIp" -ForegroundColor Green
    if ($ipAddresses.Count -gt 1) {
        Write-Host "   (Other available IPs: $($ipAddresses -join ', '))" -ForegroundColor DarkGray
    }
} else {
    Write-Host "⚠️ No external LAN IP found. Defaulting to localhost." -ForegroundColor Yellow
}

# Optional manual override prompt
Write-Host "`nDo you want to use '$detectedIp' as the API Server IP? (Press ENTER for YES or type new IP):" -ForegroundColor Cyan -NoNewline
$customIp = Read-Host " "
if (-not [string]::IsNullOrWhiteSpace($customIp)) {
    $detectedIp = $customIp.Trim()
}

$backendUrl = "http://${detectedIp}:5001"
Write-Host "`n⚙️ Configuring all platforms with API URL: $backendUrl" -ForegroundColor Cyan

# 2. Update Root .env
$rootEnvPath = "$PSScriptRoot\.env"
$rootEnvContent = @"
# Auto-generated by run-docker.ps1 on $(Get-Date)
HOST_IP=$detectedIp
BACKEND_PORT=5001
ADMIN_PORT=5003
NEXT_PUBLIC_API_BASE_URL=$backendUrl
REDIS_URL=redis://redis:6379
"@
Set-Content -Path $rootEnvPath -Value $rootEnvContent
Write-Host "  ✅ Updated: $rootEnvPath" -ForegroundColor Green

# 3. Update Admin Web .env.local
$adminEnvPath = "$PSScriptRoot\FRONTEND\Admin\.env.local"
$adminEnvContent = @"
# Auto-generated by run-docker.ps1
NEXT_PUBLIC_API_BASE_URL=$backendUrl
"@
Set-Content -Path $adminEnvPath -Value $adminEnvContent
Write-Host "  ✅ Updated: $adminEnvPath" -ForegroundColor Green

# 4. Update Flutter App .env
$flutterEnvPath = "$PSScriptRoot\FRONTEND\App\service_app\.env"
$flutterEnvContent = @"
# Auto-generated by run-docker.ps1
BASE_URL=$backendUrl
"@
Set-Content -Path $flutterEnvPath -Value $flutterEnvContent
Write-Host "  ✅ Updated: $flutterEnvPath" -ForegroundColor Green

# 5. Check if Docker is running
Write-Host "`n🐳 Checking Docker status..." -ForegroundColor Yellow
docker info > $null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Docker is not running!" -ForegroundColor Red
    Write-Host "👉 Please start Docker Desktop on your machine and run this script again." -ForegroundColor Yellow
    exit 1
}

Write-Host "✅ Docker is running and ready!" -ForegroundColor Green

# 6. Launch Docker Compose
Write-Host "`n🚀 Building and starting Docker containers..." -ForegroundColor Cyan
Write-Host "-----------------------------------------------------------------" -ForegroundColor DarkGray
Write-Host " 🌐 Admin Web Dashboard : http://localhost:5003" -ForegroundColor Magenta
Write-Host " 🌐 Admin Web (LAN/WiFi): http://${detectedIp}:5003" -ForegroundColor Magenta
Write-Host " ⚙️ Backend API Docs     : http://${detectedIp}:5001/api-docs" -ForegroundColor Magenta
Write-Host " 📱 Mobile App Target   : $backendUrl" -ForegroundColor Magenta
Write-Host "-----------------------------------------------------------------" -ForegroundColor DarkGray

docker compose up --build
