#!/bin/bash
# ==============================================================================
# Water Purifier Service Platform - Docker & Dynamic IP Automation Script (Bash)
# ==============================================================================

echo "================================================================="
echo " 🚀 Water Purifier Platform - Auto-Config & Docker Launcher"
echo "================================================================="

# 1. Detect Active IPv4 Network Address
echo -e "\n🔍 Detecting active network IP address..."

DETECTED_IP=""
if command -v ip &> /dev/null; then
    DETECTED_IP=$(ip -4 route get 8.8.8.8 2>/dev/null | awk '{print $7}')
fi

if [ -z "$DETECTED_IP" ] && command -v hostname &> /dev/null; then
    DETECTED_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
fi

if [ -z "$DETECTED_IP" ]; then
    DETECTED_IP="localhost"
    echo "⚠️ Could not auto-detect LAN IP, defaulting to localhost"
else
    echo "✅ Detected Local LAN IP: $DETECTED_IP"
fi

read -p "Use '$DETECTED_IP' as API Server IP? (Press ENTER for YES or type new IP): " USER_IP
if [ -n "$USER_IP" ]; then
    DETECTED_IP=$USER_IP
fi

BACKEND_URL="http://${DETECTED_IP}:5001"
echo -e "\n⚙️ Configuring all platforms with API URL: $BACKEND_URL"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 2. Update Root .env
cat <<EOF > "$SCRIPT_DIR/.env"
# Auto-generated by run-docker.sh
HOST_IP=$DETECTED_IP
BACKEND_PORT=5001
ADMIN_PORT=5003
NEXT_PUBLIC_API_BASE_URL=$BACKEND_URL
REDIS_URL=redis://redis:6379
EOF
echo "  ✅ Updated: $SCRIPT_DIR/.env"

# 3. Update Admin Web .env.local
cat <<EOF > "$SCRIPT_DIR/FRONTEND/Admin/.env.local"
# Auto-generated by run-docker.sh
NEXT_PUBLIC_API_BASE_URL=$BACKEND_URL
EOF
echo "  ✅ Updated: $SCRIPT_DIR/FRONTEND/Admin/.env.local"

# 4. Update Flutter App .env
cat <<EOF > "$SCRIPT_DIR/FRONTEND/App/service_app/.env"
# Auto-generated by run-docker.sh
BASE_URL=$BACKEND_URL
EOF
echo "  ✅ Updated: $SCRIPT_DIR/FRONTEND/App/service_app/.env"

# 5. Check Docker
echo -e "\n🐳 Checking Docker status..."
if ! docker info > /dev/null 2>&1; then
    echo "❌ Docker is not running! Please start Docker and run this script again."
    exit 1
fi

echo "✅ Docker is running and ready!"

# 6. Launch Docker Compose
echo -e "\n🚀 Building and starting Docker containers..."
echo "-----------------------------------------------------------------"
echo " 🌐 Admin Web Dashboard : http://localhost:5003"
echo " 🌐 Admin Web (LAN/WiFi): http://${DETECTED_IP}:5003"
echo " ⚙️ Backend API Docs     : http://${DETECTED_IP}:5001/api-docs"
echo " 📱 Mobile App Target   : $BACKEND_URL"
echo "-----------------------------------------------------------------"

docker compose up --build
